fix: 0.10.0: revert rt-compio watch channel from see back to tokio
Revert commit 093431a8d4b61f870de89efcb71e5f3f73c326f7 changes to watch
channel implementation.  The see-based watch channel had bugs, so
restore the original tokio-based implementation.

Failed test:
https://github.com/databendlabs/openraft/actions/runs/18947325145/job/54102244091?pr=1474

```
thread 'type_config::async_runtime::tokio_impls::tokio_runtime::tests::test_tokio_rt_not_singlethreaded' (2682) panicked at openraft/src/testing/runtime/mod.rs:421:20:
called `Result::unwrap()` on an `Err` value: SendError { .. }
```

It looks like it panics if send is called before recv is called:

https://github.com/databendlabs/openraft/blob/c399ac9edb63a02a12ddab9af4775fb40ad840e5/openraft/src/testing/runtime/mod.rs#L418